// MISTCODER — Live blockchain-certified scan data
// Auto-generated by blockchain/chain_exporter.py
// DO NOT EDIT — re-run chain_exporter.py to update

const DATA = {
  "scanId": "MSTC-20260422-102206-E05D7E",
  "timestamp": "2026-04-22 07:44:32 UTC",
  "findings": {
    "critical": 0,
    "high": 2,
    "medium": 0,
    "low": 0,
    "total": 2
  },
  "tkg": {
    "nodes": 65,
    "edges": 41
  },
  "chains": [
    {
      "id": "PATH-0001",
      "score": 5.0,
      "steps": 4,
      "prob": 0.512,
      "certified": false,
      "block_hash": "",
      "nodes": [
        {
          "sev": "HIGH",
          "name": "sql_query",
          "file": "analysis_engine.py",
          "line": 49,
          "cwe": "CWE-89"
        },
        {
          "sev": "HIGH",
          "name": "sql_query",
          "file": "analysis_engine.py",
          "line": 105,
          "cwe": "CWE-89"
        },
        {
          "sev": "HIGH",
          "name": "file_path",
          "file": "analysis_engine.py",
          "line": 393,
          "cwe": "CWE-22"
        },
        {
          "sev": "HIGH",
          "name": "file_path",
          "file": "analysis_engine.py",
          "line": 409,
          "cwe": "CWE-22"
        }
      ]
    },
    {
      "id": "PATH-0002",
      "score": 5.0,
      "steps": 2,
      "prob": 0.8,
      "certified": false,
      "block_hash": "",
      "nodes": [
        {
          "sev": "HIGH",
          "name": "file_path",
          "file": "analyzer.py",
          "line": 120,
          "cwe": "CWE-22"
        },
        {
          "sev": "LOW",
          "name": "file_path",
          "file": "analyzer.py",
          "line": 386,
          "cwe": "CWE-22"
        }
      ]
    },
    {
      "id": "PATH-0003",
      "score": 5.0,
      "steps": 3,
      "prob": 0.64,
      "certified": false,
      "block_hash": "",
      "nodes": [
        {
          "sev": "HIGH",
          "name": "sql_query",
          "file": "oracle_report.py",
          "line": 58,
          "cwe": "CWE-89"
        },
        {
          "sev": "HIGH",
          "name": "file_path",
          "file": "oracle_report.py",
          "line": 120,
          "cwe": "CWE-22"
        },
        {
          "sev": "HIGH",
          "name": "file_path",
          "file": "oracle_report.py",
          "line": 404,
          "cwe": "CWE-22"
        }
      ]
    },
    {
      "id": "PATH-0004",
      "score": 5.0,
      "steps": 3,
      "prob": 0.64,
      "certified": false,
      "block_hash": "",
      "nodes": [
        {
          "sev": "CRITICAL",
          "name": "eval_exec",
          "file": "test_gaps.py",
          "line": 105,
          "cwe": "CWE-94"
        },
        {
          "sev": "CRITICAL",
          "name": "eval_exec",
          "file": "test_gaps.py",
          "line": 118,
          "cwe": "CWE-94"
        },
        {
          "sev": "HIGH",
          "name": "Password",
          "file": "test_gaps.py",
          "line": 25,
          "cwe": "CWE-312"
        }
      ]
    },
    {
      "id": "PATH-0005",
      "score": 5.0,
      "steps": 4,
      "prob": 0.512,
      "certified": false,
      "block_hash": "",
      "nodes": [
        {
          "sev": "CRITICAL",
          "name": "eval_exec",
          "file": "test_parser.py",
          "line": 257,
          "cwe": "CWE-94"
        },
        {
          "sev": "HIGH",
          "name": "file_path",
          "file": "test_parser.py",
          "line": 344,
          "cwe": "CWE-22"
        },
        {
          "sev": "HIGH",
          "name": "file_path",
          "file": "test_parser.py",
          "line": 362,
          "cwe": "CWE-22"
        },
        {
          "sev": "HIGH",
          "name": "Password",
          "file": "test_parser.py",
          "line": 157,
          "cwe": "CWE-312"
        }
      ]
    },
    {
      "id": "PATH-0006",
      "score": 5.0,
      "steps": 2,
      "prob": 0.8,
      "certified": false,
      "block_hash": "",
      "nodes": [
        {
          "sev": "HIGH",
          "name": "file_path",
          "file": "phantom.py",
          "line": 375,
          "cwe": "CWE-22"
        },
        {
          "sev": "HIGH",
          "name": "file_path",
          "file": "phantom.py",
          "line": 408,
          "cwe": "CWE-22"
        }
      ]
    },
    {
      "id": "PATH-0007",
      "score": 5.0,
      "steps": 4,
      "prob": 0.512,
      "certified": false,
      "block_hash": "",
      "nodes": [
        {
          "sev": "HIGH",
          "name": "file_path",
          "file": "cve_ingester.py",
          "line": 93,
          "cwe": "CWE-22"
        },
        {
          "sev": "HIGH",
          "name": "file_path",
          "file": "cve_ingester.py",
          "line": 212,
          "cwe": "CWE-22"
        },
        {
          "sev": "HIGH",
          "name": "file_path",
          "file": "cve_ingester.py",
          "line": 220,
          "cwe": "CWE-22"
        },
        {
          "sev": "LOW",
          "name": "file_path",
          "file": "cve_ingester.py",
          "line": 232,
          "cwe": "CWE-22"
        }
      ]
    },
    {
      "id": "PATH-0008",
      "score": 5.0,
      "steps": 6,
      "prob": 0.328,
      "certified": false,
      "block_hash": "",
      "nodes": [
        {
          "sev": "HIGH",
          "name": "file_path",
          "file": "covenant.py",
          "line": 114,
          "cwe": "CWE-22"
        },
        {
          "sev": "HIGH",
          "name": "file_path",
          "file": "covenant.py",
          "line": 122,
          "cwe": "CWE-22"
        },
        {
          "sev": "HIGH",
          "name": "file_path",
          "file": "covenant.py",
          "line": 304,
          "cwe": "CWE-22"
        },
        {
          "sev": "HIGH",
          "name": "file_path",
          "file": "covenant.py",
          "line": 312,
          "cwe": "CWE-22"
        },
        {
          "sev": "HIGH",
          "name": "file_path",
          "file": "covenant.py",
          "line": 370,
          "cwe": "CWE-22"
        },
        {
          "sev": "HIGH",
          "name": "file_path",
          "file": "covenant.py",
          "line": 527,
          "cwe": "CWE-22"
        }
      ]
    },
    {
      "id": "PATH-0009",
      "score": 5.0,
      "steps": 2,
      "prob": 0.8,
      "certified": false,
      "block_hash": "",
      "nodes": [
        {
          "sev": "MEDIUM",
          "name": "High Entropy String",
          "file": "oversight_engine.py",
          "line": 432,
          "cwe": "CWE-312"
        },
        {
          "sev": "MEDIUM",
          "name": "High Entropy String",
          "file": "oversight_engine.py",
          "line": 433,
          "cwe": "CWE-312"
        }
      ]
    },
    {
      "id": "PATH-0010",
      "score": 5.0,
      "steps": 2,
      "prob": 0.8,
      "certified": false,
      "block_hash": "",
      "nodes": [
        {
          "sev": "HIGH",
          "name": "Password",
          "file": "test_oversight_engine.py",
          "line": 29,
          "cwe": "CWE-312"
        },
        {
          "sev": "MEDIUM",
          "name": "High Entropy String",
          "file": "test_oversight_engine.py",
          "line": 274,
          "cwe": "CWE-312"
        }
      ]
    },
    {
      "id": "PATH-0011",
      "score": 5.0,
      "steps": 3,
      "prob": 0.64,
      "certified": false,
      "block_hash": "",
      "nodes": [
        {
          "sev": "HIGH",
          "name": "file_path",
          "file": "run_reasoning.py",
          "line": 39,
          "cwe": "CWE-22"
        },
        {
          "sev": "HIGH",
          "name": "file_path",
          "file": "run_reasoning.py",
          "line": 40,
          "cwe": "CWE-22"
        },
        {
          "sev": "HIGH",
          "name": "file_path",
          "file": "run_reasoning.py",
          "line": 67,
          "cwe": "CWE-22"
        }
      ]
    },
    {
      "id": "PATH-0012",
      "score": 5.0,
      "steps": 2,
      "prob": 0.8,
      "certified": false,
      "block_hash": "",
      "nodes": [
        {
          "sev": "MEDIUM",
          "name": "Weak Hash",
          "file": "attack_graph.py",
          "line": 127,
          "cwe": "CWE-327"
        },
        {
          "sev": "MEDIUM",
          "name": "Weak Hash",
          "file": "attack_graph.py",
          "line": 127,
          "cwe": "CWE-327"
        }
      ]
    },
    {
      "id": "PATH-0013",
      "score": 5.0,
      "steps": 5,
      "prob": 0.41,
      "certified": false,
      "block_hash": "",
      "nodes": [
        {
          "sev": "HIGH",
          "name": "sql_query",
          "file": "reasoning.py",
          "line": 301,
          "cwe": "CWE-89"
        },
        {
          "sev": "HIGH",
          "name": "file_path",
          "file": "reasoning.py",
          "line": 552,
          "cwe": "CWE-22"
        },
        {
          "sev": "HIGH",
          "name": "file_path",
          "file": "reasoning.py",
          "line": 553,
          "cwe": "CWE-22"
        },
        {
          "sev": "MEDIUM",
          "name": "High Entropy String",
          "file": "reasoning.py",
          "line": 164,
          "cwe": "CWE-312"
        },
        {
          "sev": "LOW",
          "name": "file_path",
          "file": "reasoning.py",
          "line": 532,
          "cwe": "CWE-22"
        }
      ]
    },
    {
      "id": "PATH-0014",
      "score": 5.0,
      "steps": 2,
      "prob": 0.8,
      "certified": false,
      "block_hash": "",
      "nodes": [
        {
          "sev": "HIGH",
          "name": "file_path",
          "file": "cvss_scorer.py",
          "line": 472,
          "cwe": "CWE-22"
        },
        {
          "sev": "HIGH",
          "name": "file_path",
          "file": "cvss_scorer.py",
          "line": 484,
          "cwe": "CWE-22"
        }
      ]
    }
  ],
  "owasp": [
    {
      "name": "A01: Broken Access Control",
      "hits": 28,
      "max": 30
    },
    {
      "name": "A02: Cryptographic Failures",
      "hits": 9,
      "max": 30
    },
    {
      "name": "A03: Injection",
      "hits": 7,
      "max": 30
    }
  ],
  "cwe": [
    {
      "id": "CWE-22",
      "rank": "#8",
      "hits": 28
    },
    {
      "id": "CWE-312",
      "rank": "#13",
      "hits": 7
    },
    {
      "id": "CWE-89",
      "rank": "#1",
      "hits": 4
    },
    {
      "id": "CWE-94",
      "rank": "#28",
      "hits": 3
    },
    {
      "id": "CWE-327",
      "rank": "#0",
      "hits": 2
    }
  ],
  "files": [
    {
      "name": "test_gaps.py",
      "crit": 2,
      "high": 1,
      "total": 3
    },
    {
      "name": "test_parser.py",
      "crit": 1,
      "high": 3,
      "total": 4
    },
    {
      "name": "covenant.py",
      "crit": 0,
      "high": 6,
      "total": 6
    },
    {
      "name": "analysis_engine.py",
      "crit": 0,
      "high": 4,
      "total": 4
    },
    {
      "name": "oracle_report.py",
      "crit": 0,
      "high": 3,
      "total": 3
    },
    {
      "name": "cve_ingester.py",
      "crit": 0,
      "high": 3,
      "total": 4
    },
    {
      "name": "run_reasoning.py",
      "crit": 0,
      "high": 3,
      "total": 3
    },
    {
      "name": "reasoning.py",
      "crit": 0,
      "high": 3,
      "total": 5
    },
    {
      "name": "phantom.py",
      "crit": 0,
      "high": 2,
      "total": 2
    },
    {
      "name": "cvss_scorer.py",
      "crit": 0,
      "high": 2,
      "total": 2
    }
  ],
  "remediation": [
    {
      "num": 1,
      "cwe": "CWE-22",
      "effort": "LOW",
      "action": "Validate and canonicalize all file paths \u2014 use Path.resolve() + allowlist"
    },
    {
      "num": 2,
      "cwe": "CWE-312",
      "effort": "MEDIUM",
      "action": "Audit hardcoded credentials \u2014 rotate secrets, migrate to env vars / vault"
    },
    {
      "num": 3,
      "cwe": "CWE-89",
      "effort": "LOW",
      "action": "Parameterize all SQL queries \u2014 use ORM or prepared statements throughout"
    },
    {
      "num": 4,
      "cwe": "CWE-94",
      "effort": "HIGH",
      "action": "Remove eval/exec on untrusted input \u2014 use AST-safe parsers or sandboxed eval"
    },
    {
      "num": 5,
      "cwe": "CWE-327",
      "effort": "LOW",
      "action": "Replace MD5/SHA1/DES with SHA-256+ or AES-256 \u2014 one-line swap in hashlib"
    }
  ],
  "ledger": [
    {
      "num": 0,
      "hash": "0005f8305c1ce6f01409\u2026",
      "time": "2026-04-24T20:38:39",
      "findings": 2,
      "paths": 0
    },
    {
      "num": 1,
      "hash": "0004651f9f3ebe717e93\u2026",
      "time": "2026-04-24T20:38:39",
      "findings": 2,
      "paths": 1
    },
    {
      "num": 2,
      "hash": "00049773246125cabd89\u2026",
      "time": "2026-04-24T20:38:39",
      "findings": 2,
      "paths": 1
    },
    {
      "num": 3,
      "hash": "000dbad6e5eb17da3869\u2026",
      "time": "2026-04-24T20:38:39",
      "findings": 2,
      "paths": 1
    },
    {
      "num": 4,
      "hash": "00066b67b919e5d5f924\u2026",
      "time": "2026-04-24T20:38:39",
      "findings": 2,
      "paths": 1
    },
    {
      "num": 5,
      "hash": "000aeeb21b87f1d3195f\u2026",
      "time": "2026-04-24T20:38:39",
      "findings": 2,
      "paths": 1
    },
    {
      "num": 6,
      "hash": "000c6486e5be224b9aec\u2026",
      "time": "2026-04-24T20:38:39",
      "findings": 2,
      "paths": 1
    },
    {
      "num": 7,
      "hash": "00021478f92e554340c8\u2026",
      "time": "2026-04-24T20:38:39",
      "findings": 2,
      "paths": 1
    },
    {
      "num": 8,
      "hash": "0003906938456a4195e7\u2026",
      "time": "2026-04-24T20:38:39",
      "findings": 2,
      "paths": 1
    },
    {
      "num": 9,
      "hash": "000ab2da0968705c9d80\u2026",
      "time": "2026-04-24T20:38:40",
      "findings": 2,
      "paths": 1
    },
    {
      "num": 10,
      "hash": "000896e52d1ac2363687\u2026",
      "time": "2026-04-24T20:38:40",
      "findings": 2,
      "paths": 1
    },
    {
      "num": 11,
      "hash": "000a9c6badb86771125a\u2026",
      "time": "2026-04-24T20:38:40",
      "findings": 2,
      "paths": 1
    },
    {
      "num": 12,
      "hash": "000a5930d65138f08a4a\u2026",
      "time": "2026-04-24T20:38:40",
      "findings": 2,
      "paths": 1
    },
    {
      "num": 13,
      "hash": "000c4de6946daa66009c\u2026",
      "time": "2026-04-24T20:38:40",
      "findings": 2,
      "paths": 1
    },
    {
      "num": 14,
      "hash": "000311a788e2719736c6\u2026",
      "time": "2026-04-24T20:38:40",
      "findings": 2,
      "paths": 1
    },
    {
      "num": 15,
      "hash": "00013157210c0fb99635\u2026",
      "time": "2026-04-24T20:38:44",
      "findings": 2,
      "paths": 1
    },
    {
      "num": 16,
      "hash": "00026df33f9d73c5fdb5\u2026",
      "time": "2026-04-24T20:38:44",
      "findings": 2,
      "paths": 1
    },
    {
      "num": 17,
      "hash": "0006c7234f23a18ad204\u2026",
      "time": "2026-04-24T20:38:44",
      "findings": 2,
      "paths": 1
    },
    {
      "num": 18,
      "hash": "000ffa3828fafe8b5f5b\u2026",
      "time": "2026-04-24T20:38:45",
      "findings": 2,
      "paths": 1
    },
    {
      "num": 19,
      "hash": "0009e728ab866d09831d\u2026",
      "time": "2026-04-24T20:38:45",
      "findings": 2,
      "paths": 1
    },
    {
      "num": 20,
      "hash": "0002821f3ef2122df026\u2026",
      "time": "2026-04-24T20:38:45",
      "findings": 2,
      "paths": 1
    },
    {
      "num": 21,
      "hash": "0009e7c11eaadb43d43e\u2026",
      "time": "2026-04-24T20:38:45",
      "findings": 2,
      "paths": 1
    },
    {
      "num": 22,
      "hash": "00047e100d0a683ae39b\u2026",
      "time": "2026-04-24T20:38:45",
      "findings": 2,
      "paths": 1
    },
    {
      "num": 23,
      "hash": "000d1427cf094b5e2cdc\u2026",
      "time": "2026-04-24T20:38:46",
      "findings": 2,
      "paths": 1
    },
    {
      "num": 24,
      "hash": "0009c33a30c0e7be49c7\u2026",
      "time": "2026-04-24T20:38:46",
      "findings": 2,
      "paths": 1
    },
    {
      "num": 25,
      "hash": "0007b6911a2dfd4bea69\u2026",
      "time": "2026-04-24T20:38:46",
      "findings": 2,
      "paths": 1
    },
    {
      "num": 26,
      "hash": "00021c9316eca08e7a9c\u2026",
      "time": "2026-04-24T20:38:46",
      "findings": 2,
      "paths": 1
    },
    {
      "num": 27,
      "hash": "00053d66452e15874ea9\u2026",
      "time": "2026-04-24T20:38:46",
      "findings": 2,
      "paths": 1
    },
    {
      "num": 28,
      "hash": "0009b87c9ecf97722b69\u2026",
      "time": "2026-04-24T20:38:46",
      "findings": 2,
      "paths": 1
    },
    {
      "num": 29,
      "hash": "0005c0a97569380a3e94\u2026",
      "time": "2026-04-24T20:38:59",
      "findings": 2,
      "paths": 1
    },
    {
      "num": 30,
      "hash": "000cd75491f9c28c23d0\u2026",
      "time": "2026-04-24T20:39:00",
      "findings": 2,
      "paths": 1
    },
    {
      "num": 31,
      "hash": "000f8492e6cc7dca0962\u2026",
      "time": "2026-04-24T20:39:00",
      "findings": 2,
      "paths": 1
    },
    {
      "num": 32,
      "hash": "000285de240bfd606cae\u2026",
      "time": "2026-04-24T20:39:00",
      "findings": 2,
      "paths": 1
    },
    {
      "num": 33,
      "hash": "0004d5bb6d71cc0743e7\u2026",
      "time": "2026-04-24T20:39:00",
      "findings": 2,
      "paths": 1
    },
    {
      "num": 34,
      "hash": "0002a5aa18a2271565f1\u2026",
      "time": "2026-04-24T20:39:01",
      "findings": 2,
      "paths": 1
    },
    {
      "num": 35,
      "hash": "0000c9e3c218a1be1997\u2026",
      "time": "2026-04-24T20:39:01",
      "findings": 2,
      "paths": 1
    },
    {
      "num": 36,
      "hash": "000be005903b87d8f91c\u2026",
      "time": "2026-04-24T20:39:01",
      "findings": 2,
      "paths": 1
    },
    {
      "num": 37,
      "hash": "00014b38131c3d18ce3b\u2026",
      "time": "2026-04-24T20:39:01",
      "findings": 2,
      "paths": 1
    },
    {
      "num": 38,
      "hash": "000abf7e076fb1545b22\u2026",
      "time": "2026-04-24T20:39:01",
      "findings": 2,
      "paths": 1
    },
    {
      "num": 39,
      "hash": "000592a5f1d7bb698d42\u2026",
      "time": "2026-04-24T20:39:01",
      "findings": 2,
      "paths": 1
    },
    {
      "num": 40,
      "hash": "000ef9d59c860ebacfcc\u2026",
      "time": "2026-04-24T20:39:01",
      "findings": 2,
      "paths": 1
    },
    {
      "num": 41,
      "hash": "0003daf7dfc5cec45160\u2026",
      "time": "2026-04-24T20:39:01",
      "findings": 2,
      "paths": 1
    },
    {
      "num": 42,
      "hash": "000ac736409c7163d141\u2026",
      "time": "2026-04-24T20:39:02",
      "findings": 2,
      "paths": 1
    },
    {
      "num": 43,
      "hash": "000838dfd0f4cb72d23c\u2026",
      "time": "2026-04-24T20:41:44",
      "findings": 2,
      "paths": 1
    },
    {
      "num": 44,
      "hash": "0006e3d7f2becf05f6ec\u2026",
      "time": "2026-04-24T20:41:44",
      "findings": 2,
      "paths": 1
    },
    {
      "num": 45,
      "hash": "000419ec7b7e9b0fc31e\u2026",
      "time": "2026-04-24T20:41:44",
      "findings": 2,
      "paths": 1
    },
    {
      "num": 46,
      "hash": "0009cd6b2fbca938a1a5\u2026",
      "time": "2026-04-24T20:41:45",
      "findings": 2,
      "paths": 1
    },
    {
      "num": 47,
      "hash": "000270d2cdd1c0f72539\u2026",
      "time": "2026-04-24T20:41:45",
      "findings": 2,
      "paths": 1
    },
    {
      "num": 48,
      "hash": "0003ee0a74bffb8ef048\u2026",
      "time": "2026-04-24T20:41:45",
      "findings": 2,
      "paths": 1
    },
    {
      "num": 49,
      "hash": "0009c6c8410f2845269e\u2026",
      "time": "2026-04-24T20:41:45",
      "findings": 2,
      "paths": 1
    },
    {
      "num": 50,
      "hash": "000357f079376ecdcbbb\u2026",
      "time": "2026-04-24T20:41:45",
      "findings": 2,
      "paths": 1
    },
    {
      "num": 51,
      "hash": "000cace60d1b94cea667\u2026",
      "time": "2026-04-24T20:41:46",
      "findings": 2,
      "paths": 1
    },
    {
      "num": 52,
      "hash": "0001cd910a7fe7fb782d\u2026",
      "time": "2026-04-24T20:41:46",
      "findings": 2,
      "paths": 1
    },
    {
      "num": 53,
      "hash": "000350f39e1309759e7f\u2026",
      "time": "2026-04-24T20:41:46",
      "findings": 2,
      "paths": 1
    },
    {
      "num": 54,
      "hash": "000f68d2c0ee9a2ca759\u2026",
      "time": "2026-04-24T20:41:46",
      "findings": 2,
      "paths": 1
    },
    {
      "num": 55,
      "hash": "000271893681ae1805dc\u2026",
      "time": "2026-04-24T20:41:46",
      "findings": 2,
      "paths": 1
    },
    {
      "num": 56,
      "hash": "000f0ff7aa5b1a1cf726\u2026",
      "time": "2026-04-24T20:41:47",
      "findings": 2,
      "paths": 1
    }
  ],
  "mitre": [
    {
      "tactic": "TA0007",
      "name": "Discovery",
      "techniques": [
        "T1083 - File & Directory Discovery"
      ]
    },
    {
      "tactic": "TA0006",
      "name": "Credential Access",
      "techniques": [
        "T1552 - Unsecured Credentials"
      ]
    },
    {
      "tactic": "TA0001",
      "name": "Initial Access",
      "techniques": [
        "T1190 - Exploit Public-Facing App"
      ]
    },
    {
      "tactic": "TA0002",
      "name": "Execution",
      "techniques": [
        "T1059 - Command & Script Interpreter"
      ]
    },
    {
      "tactic": "TA0040",
      "name": "Impact",
      "techniques": [
        "T1565 - Data Manipulation"
      ]
    }
  ],
  "blockchain": {
    "blocks": 57,
    "certified": 0,
    "blocked": 0,
    "integrity": "VERIFIED"
  }
};
